version: '3'

services:
  db:
    image: mongo
    restart: always
    volumes:
      - db-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://user:pass@db:27017/

  api:
    build: ./api
    restart: always
    env_file:
      - ./api/.env
    ports:
      - 3000:3000
    environment:
      DB_URI: mongodb://user:pass@db:27017
      JWT_SECRET: jwt-secret
      ADMIN_USER: admin
      ADMIN_PASS: admin

  agent:
    build: ./agent
    restart: always
    env_file:
      - ./agent/.env
    environment:
      #ROUTER_TYPE:
      #ROUTER_URL:
      #ROUTER_ADMIN_USER:
      #ROUTER_ADMIN_PASS:
      #AGENT_ID:
      #AGENT_SECRET:
      COORDINATOR_URL: http://api:3000/api
      WIFI_CLIENTS_REPORT_INTERVAL: 30

  web:
    build: ./web
    restart: always
    ports:
      - 80:80

volumes:
  db-data:
