version: '3'

services:
  db:
    image: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=router-monitor
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    restart: always
    ports:
      - 3306:3306
