name: Build Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [agent, api, web]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName
        with:
          tagRegex: "v(.*)"
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get version number
        id: vars
        run: echo ::set-output name=version::${GITHUB_REF_NAME##*/}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: yarn build:${{ matrix.project }}
#      - name: Push
#        run: yarn build:${{ matrix.project }}
