name: Build
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project: agent
            platform: linux/arm/v7,linux/arm64/v8,linux/amd64
            setup-qemu: true
          - project: api
            platform: linux/amd64
            setup-qemu: false
          - project: web
            platform: linux/amd64
            setup-qemu: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: ${{ matrix.setup-qemu }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        run: docker buildx build --load --platform ${{ matrix.platform }} --build-arg VERSION=test --tag vanflux/rm-${{ matrix.project }} ${{ matrix.project }}
