name: Build
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [agent, api, web]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        run: docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --build-arg VERSION=test --tag vanflux/rm-${{ matrix.project }} ${{ matrix.project }}
